### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by ffquintella**
This fixes some bugs 

The last 2 ones are a bug on the filter javascript library where the selection always got back

And the last one is a implode funcion using an old signature (deprecated on php 7.4 and removed on php 8)

### CODE REVIEW

**Comment by jsokol** [comment]
I've got three of these ready to go live in the next release (likely tomorrow), but I wanted to see if you could provide more information about this one:

https://github.com/simplerisk/code/pull/36/commits/d63252a4914f89f0e94d720f7debd4f3a2e6ce96

What exactly is the issue here and how do you trigger it?  It seems unlikely that this code was included unintentionally so I want to make sure I understand that before incorporating the change.  Thanks!

**Comment by ffquintella** [comment]
In Goverance when filtering the controls every time we tried to select some control families it ignored the selection and appeared with all selected again. I noticed it was reloading the data and getting them selected at every change. comiting this part solved the problem.

**Comment by jsokol** [comment]
When you say "getting them selected at every change" are you talking about when you select another filter or are you talking about when you edit and save a control or something else?  I haven't been able to replicate this issue, which makes me think maybe I'm not doing the same thing that you are.  Can you maybe provide more explicit instructions or, perhaps, a video of what you're encountering here?  Thanks!

**Comment by ffquintella** [comment]
This only happens on the filter.

image

The image shows where the problem occurs.

**Comment by jsokol** [comment]
To be honest, I'm still unsure what the bug is that you're seeing here.  If I go to my instance and just view it by default, I see all control families selected, by default:

Screen Shot 2022-06-30 at 3 24 01 PM

I then unchecked "Select All" and selected my "Asset Management" control family and clicked out of the filter and the page updates to show the relevant controls for that family:

Screen Shot 2022-06-30 at 3 25 59 PM

I've tried editing controls and the filter stays the same.  I can select other filters and it seems to filter properly.  I'm having trouble determining what you believe the issue is there and why you expect it to behave differently than it does currently.  Is this not how you would expect the functionality to work?

**Comment by ffquintella** [comment]
It´s weird you are having a different behavior then what we see here maybe because we are running on php 8?

**Comment by ffquintella** [comment]
Shure we are able to use it with php8.1 with just a few glitches the fixes I sent you solves almost all problems we found so far.

**Pull request closed without merging**
